# Generated by Django 5.2 on 2025-05-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.test'),
            preserve_default=False,
        ),
    ]
