# Generated by Django 5.2 on 2025-05-23 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_option_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='why_is_correct',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tests.test'),
            preserve_default=False,
        ),
    ]
