# Generated by Django 5.2 on 2025-05-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_option_why_is_correct_useranswer_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('LÓGICA MATEMÁTICA', 'Lógica Matemática'), ('RAZONAMIENTO VERBAL', 'Razonamiento Verbal')], max_length=50),
        ),
    ]
