# Generated by Django 5.2 on 2025-05-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='why_is_correct',
            field=models.TextField(default='porque si'),
            preserve_default=False,
        ),
    ]
