# Generated by Django 5.2 on 2025-05-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_option_why_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='why_is_correct',
        ),
    ]
