# Generated by Django 5.2 on 2025-05-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_remove_option_why_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='prueba',
            field=models.BooleanField(default=False),
        ),
    ]
