# Generated by Django 5.2 on 2025-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_option_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='prueba',
        ),
        migrations.AddField(
            model_name='option',
            name='why_is_correct',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
