# Generated by Django 5.2 on 2025-05-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_remove_option_prueba_option_why_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='why_is_correct',
            field=models.TextField(),
        ),
    ]
