# Generated by Django 5.2 on 2025-05-25 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_option_why_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='options',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='options',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tests.option'),
            preserve_default=False,
        ),
    ]
