# Generated by Django 5.2 on 2025-05-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_remove_useranswer_options_useranswer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='options',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='options',
            field=models.ManyToManyField(blank=True, to='tests.option'),
        ),
    ]
