# Generated by Django 5.2 on 2025-05-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.TextField()),
                ('category', models.CharField(choices=[('LÓGICA MATEMÁTICA', 'Lógica Matemática'), ('RAZONAMIENTO VERBAL', 'Razonamiento Verbal')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cont_practice', to='practices.practice')),
            ],
        ),
    ]
