# Generated by Django 5.2 on 2025-05-24 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_contpractice_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('cont_practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='practices.contpractice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
